version: "3"

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./mindfile.db:/app/mindfile.db
    environment:
      - DATABASE_URL=sqlite:///./mindfile.db
      - UPLOAD_DIR=./uploads
      - FIRST_ADMIN_EMAIL=admin@example.com
      - FIRST_ADMIN_PASSWORD=admin123

  frontend:
    image: node:14
    working_dir: /app
    command: bash -c "npm install && npm run serve"
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"
    environment:
      - VUE_APP_API_URL=http://localhost:8000/api
